### ISSUE TITLE
Problem with Peter Collingswood's 3D module wireframeDisplay 

### ISSUE THREAD

**Issue by nickums** [petercollingridge/Pygame3D#1]
Being interested in pygame, I have installed Peter Collingridge's set of wireframe 3D modules.
Unfortunately when they try and display an image, I get: 
module 'wireframeDisplay' has no attribute 'wireframe'
and I don't know how to fix this.

**Comment by Rufmemory** [comment]
Well i think here might be a big thing with converting code to python 3, allthough i might be wrong.
But this is really some very polished, detailed and mathematically amaizing code... anyway i cannot even describe well enough how awesome i think that code is. 
Yet it is not perfect and depending on your platform you may want to do some effort in making it work. 
I am trying to make an all in 1 module of objects, wireframe and viewer but it is quite the task i might say. And if and when it works i will definetly submit it as a pull request. 
Again this really is a wonderfull work. 
Sincerly. Ruf.

**Comment by nickums** [comment]
I am now using OpenGl so am no longer attempting to use Peter's wireframe package
